import Head from "next/head";
import React, { useEffect, useState } from 'react'
import Add from '../pages/add.js';
import Card from '../pages/cards.js';
import axios from 'axios';
import 'bootstrap/dist/css/bootstrap.min.css'
import Image from "next/image.js";
import githubImage from "../../public/github.svg";
import toast, { Toaster } from 'react-hot-toast';

export default function Home() {
  const api = "https://jsonplaceholder.typicode.com";
  const [apiData, getApiData] = useState([]);
  const [addData, getAddDat] = useState({ addTitle: "", addDescription: "" });

  useEffect(() => {
    getUserData();
  }, []);

  const getUserData = async () => {
    try {
      const response = await axios.get(api + "/posts");
      getApiData(response.data);
    } catch (error) {
      console.log(error.message);
      console.log(error.response.data);
      console.log(error.response.status);
    }
  }

  const handleDelete = async (id) => {
    try {
      const responseApi = await axios.delete(api + `/posts/${id}`);
      if (responseApi.status === 200) {
        const filterCard = apiData.filter((currentItem) => currentItem.id !== id);
        getApiData(filterCard);
        toast.success('Successfully deleted!');
      }
    } catch (error) {
      console.log(error.message);
      console.log(error.response.data);
      console.log(error.response.status);
    }
  }

  const handleInputChange = (event) => {
    const name = event.target.name;
    const value = event.target.value;
    getAddDat({ ...addData, [name]: value.toLowerCase().trim() }); //[name]:value update dynamic value 
  }

  const handleAdd = async () => {
    try {
      const object = {
        body: addData.addDescription,
        id: "",
        title: addData.addTitle,
        userId: Date.now()
      }
      const response = await axios.post(api + "/posts", object);
      toast.success('Successfully created!');
      getApiData([...apiData, response.data]); //response one object copying in apidata and syntax create new array
    } catch (error) {
      console.log(error.message);
      console.log(error.response.data);
      console.log(error.response.status);
    }
  }

  return (
    <>
      <Head>
        <title>Axios + Curd + Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-secondary p-2">
        <header className='d-flex justify-content-center'>
          <a href="https://github.com/Nandakishore695/axios-curd-project">
            <Image src={githubImage} alt="gitHub Nandakishore695" width={70} className="float-right" />
          </a>
          <h1 className='text-white m-4'>Vite + React + Axios + Curd</h1>
        </header>
        <div className='container  text-center '>
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          <Add handleInputChange={handleInputChange} handleAdd={handleAdd} />
          <Card apiDataObjectProps={apiData} handleDelete={handleDelete} />
        </div>

      </main>


    </>
  );
}
